# Generated by Django 4.0.1 on 2022-02-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('open_hour', models.SmallIntegerField()),
                ('close_hour', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('director', models.CharField(max_length=100)),
            ],
        ),
    ]
