# Generated by Django 4.0.1 on 2022-02-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=14)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=14)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
